#!/bin/bash

case "$1" in 
start)
   /home/cdot/CFW_NFV_BASE_SUB_PATH/CFW_NFV_CONTROLLER_DIR/NFV/attach_volumes.sh &
   echo $!>/var/run/attach_volumes.pid
   ;;
stop)
   kill `cat /var/run/attach_volumes.pid`
   rm /var/run/attach_volumes.pid
   ;;
restart)
   $0 stop
   $0 start
   ;;
status)
   if [ -e /var/run/attach_volumes.pid ]; then
      echo attach_volumes.sh is running, pid=`cat /var/run/attach_volumes.pid`
   else
      echo attach_volumes.sh is NOT running
      exit 1
   fi
   ;;
*)
   echo "Usage: $0 {start|stop|status|restart}"
esac

exit 0 
