[pytest]
minversion = 6.0
addopts = -ra -q --tb=short --maxfail=1 --show-capture=no
testpaths = tests

markers =
    launch_instance: TEOSM Web GUI NS Instance launch automation pipeline tests
    clean_teosm_gui_cloud_volume_image: TEOSM Web GUI and Cloud storage teardown pipeline tests
    gui_login: TEOSM and Cloud Horizon Web GUI login authentication tests
    node_launch: End-to-end Node Launch automation pipeline tests
    remote: Tests requiring live SSH remote host connectivity
    local: Unit tests running locally on controller host

log_cli = true
log_cli_level = INFO
log_cli_format = %(asctime)s [%(levelname)s] %(message)s (%(filename)s:%(lineno)s)
log_cli_date_format = %Y-%m-%d %H:%M:%S
